- name: Parse to obtain commands
  cisco.ios.ios_acls:
    config:
      - afi: ipv4
        acls:
          - name: 110
            aces:
              - grant: deny
                protocol: tcp
                protocol_options:
                  tcp:
                    ack: true
                sequence: 10
                source:
                  address: 198.51.100.0
                  wildcard_bits: 0.0.0.255
                  port_protocol:
                    eq: telnet
                destination:
                  address: 198.51.110.0
                  wildcard_bits: 0.0.0.255
                  port_protocol:
                    eq: www
                dscp: ef
                ttl:
                  eq: 10
          - name: 123
            aces:
              - grant: deny
                sequence: 10
                protocol: tcp
                protocol_options:
                  tcp:
                    ack: true
                source:
                  address: 198.51.100.0
                  wildcard_bits: 0.0.0.255
                destination:
                  address: 198.51.101.0
                  wildcard_bits: 0.0.0.255
                  port_protocol:
                    eq: telnet
                tos:
                  service_value: 12
          - name: 150
            aces:
              - grant: deny
                sequence: 10
                protocol: tcp
                protocol_options:
                  tcp:
                    syn: true
                source:
                  address: 198.51.100.0
                  wildcard_bits: 0.0.0.255
                  port_protocol:
                    eq: telnet
                destination:
                  address: 198.51.110.0
                  wildcard_bits: 0.0.0.255
                  port_protocol:
                    eq: telnet
                dscp: ef
                ttl:
                  eq: 10
    state: rendered
  register: acl_data

- name: Display variables
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ acl_data.rendered }}"

- name: Generate config lines to negate templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - {
          src: "{{ playbook_dir }}/roles/config_acl_popper/templates/acl_template.j2",
          dest: "{{ playbook_dir }}/vars/acl_config.cfg",
      }

- name: Negate ace configuration per acl
  cisco.ios.ios_config:
    src: "{{ playbook_dir }}/vars/acl_config.cfg"
