- name: Parse to obtain commands
  cisco.ios.ios_acls:
    config: "{{ acls_data }}"
    state: rendered
  register: acl_data

- name: Display variables
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ acl_data.rendered }}"

- name: Generate config lines to negate templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - {
          src: "{{ playbook_dir }}/roles/config_acl_popper/templates/acl_template.j2",
          dest: "{{ playbook_dir }}/vars/acl_config.cfg",
      }

- name: Negate ace configuration per acl
  cisco.ios.ios_config:
    src: "{{ playbook_dir }}/vars/acl_config.cfg"
